### ISSUE TITLE
Wifi Direct does not appear to work

### ISSUE THREAD

**Issue by infernix** [TeamApexQ/apexq#26]
Something in the code is looking for /data/misc/wifi/sockets/p2p0 but the actual socket is made at /data/misc/wifi/p2p0.

Also, even with a symlink it does not appear to be working; as in, there is no access point appearing for other devices. But I do not have another wifi direct supporting device to test with.

**Comment by lbdroid** [comment]
Solved with https://github.com/lbdroid/vendor_samsung_apexqtmo/commit/5d35cbc372c7c79d14913d106c991406705098a2

**Comment by nardholio** [comment]
xda is reporting this is still an issue. we may need to symlink the socket or figure out why it's looking in the wrong place

**Comment by lbdroid** [comment]
http://forum.xda-developers.com/showpost.php?p=43116928&postcount=13
Test invalid. There is no indication of it not working.
