### ISSUE TITLE
Compass Calibration

### ISSUE THREAD

**Issue by b3orion** [TeamApexQ/apexq#7]
I see that the compass calibration is off... very off. 
Apparently it is the same issue in the stock rom, as it has been reported happening on it too. 
The heading/baring is usually about 190 degrees off, and the magnetic field strength is crazy high, as seen in the screenshot.

Calibrating in the "GPS Status and Toolbox" app, seems to work until I reboot, then it resets back to the inaccurate readings. I don't know if it is a simple fix in the ROMs, or if it hardware.
![Screenshot_2013-01-31-21-12-15](https://f.cloud.github.com/assets/3087072/117251/26e0ced8-6c2e-11e2-947e-d0c13500bd05.png)

**Comment by infernix** [comment]
This is potentially fixed in https://github.com/TeamApexQ/android_kernel_samsung_apexq/commit/030b23309c31f082dc0cdc93098b861021163631 - can you try a recent build and retest? Nightly builds link is on the main wiki page.

**Comment by b3orion** [comment]
I downloaded and flashed cm-10.1-20130312-NIGHTLY-apexqtmo this morning.
Tested, and I am still having the calibration issue, so I went back to CM9. Did I test the correct build? I chose the most recent one I could find!
![Screenshot_2013-03-12-09-17-54](https://f.cloud.github.com/assets/3087072/249743/42e86ef2-8b36-11e2-9b83-1867f8fc7da8.png)

**Comment by infernix** [comment]
Yes, that's a valid build. It's still broken then.

**Comment by infernix** [comment]
yas532 kernel code looks for /efs/calibration_data which is missing at bootup.
However, mpu also looks for this same file, so it's not clear which one the kernel is complaining about:

<pre>
<3>[    9.573599] accel_open_calibration: Can't open calibration file
</pre>

this file is nowhere to be found. The only file we have is /efs/FactoryData/baro_delta which is referenced for _other_ sensors, e.g. bmp180. There is also nothing in the stock app that will write to that file. libyamaha.so also has no reference to this file.

This:

<pre>
05-14 15:18:56.187 I/MPL-mlsl(  688): inv_serial_open: /dev/mpu
<6>[    9.579093] Sensors unset: 7fff
<3>[    9.580344] /var/lib/jenkins/jobs/apexq/android/jellybean/kernel/samsung/apexq/drivers/misc/inv_mpu/mldl_cfg.c|inv_mpu_get_slave_config|2038 returning 36
05-14 15:18:56.187 I/MPL-mldl_cfg_mpu:(  688): inv_mpu_suspend(,,,,7fff) -> 0000
05-14 15:18:56.197 E/        (  688): ../../mldl_cfg_mpu.c|inv_mpu_get_slave_config|863 returning -1
05-14 15:18:56.197 E/        (  688): ../../compass.c|inv_compass_read_scale|328 returning 255
</pre>

appears to come from libmllite hardware/invensense/mlsdk/mllite/mldl_cfg_mpu.c.
Return code 36 is INV_ERROR_FEATURE_NOT_IMPLEMENTED

Then this:

<pre>
05-14 15:18:56.197 V/Sensors (  688): Calibration file successfully loaded
</pre>

is returned by:
./hardware/invensense/libsensors_iio/MPLSensor.cpp:        LOGV_IF(PROCESS_VERBOSE, "HAL:Calibration file successfully loaded");

The puzzling part is:

<pre>
05-14 15:18:56.197 E/Sensors (  688): h_yamaha_lib=0x40044c90, error=Symbol not found: 
05-14 15:18:56.197 E/        (  688): pYamahaData : 0x40c7f1a0
05-14 15:18:56.197 V/Sensors (  688): MPLSensor::getFd returning 30
05-14 15:18:56.197 V/Sensors (  688): MPLSensor::getAccelFd returning -1
05-14 15:18:56.197 V/Sensors (  688): MPLSensor::getTimerFd returning 31
</pre>

h_yamaha_lib part of a function in libinvensense_hal.so. pYamahaData is a symbol in libyamaha.so:

<pre>
     4: 00008168     4 OBJECT  LOCAL  DEFAULT   13 pYamahaData
</pre>

so it is definitely present.

**Comment by infernix** [comment]
Datasheet: http://download.yamaha.com/file/52799

**Comment by lbdroid** [comment]
This makes it _better_ enough to call "solved":
https://github.com/lbdroid/vendor_samsung_apexqtmo/commit/4972a4d49433a5b68452cf6786fc89fc6a9085d5
